# Generated by Django 5.0.1 on 2024-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
